In [1]:
# Write a program that will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). 
# The numbers obtained should be printed in a comma-separated sequence on a single line. 

for x in range(2000, 3200):
    if (x%7 == 0):
        if (x%5 !=0):
            print(x, end = ", ")

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199, 

In [3]:
# Write a program that takes 2 digits, X, Y as input and generates a 2-dimensional array. 
# The element value in the i-th row and j-th column of the array should be i*j. Note: i=0,1.., X-1; j=0,1,¡-Y-1. 

import numpy as np


x = int(input("Value of X : "))
y = int(input("Value of Y : "))

x = int(x)
y = int(y)
arr = np.zeros((x, y), dtype=int)

for a in range(x):
    for b in range(y):
        arr[a,b] = a*b

print(arr)

Value of X :  5
Value of Y :  6


[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]]


In [2]:
#  Write a program that accepts a comma-separated sequence of words as input and prints the words in a 
# comma-separated sequence after sorting them alphabetically.  

i = int(input("Enter the number of words you want to input :"))
print (i)
li = []
for x in range (i):
    li.append(input("Word :"))
li.sort()
for x in li:
    print (x, end = ", ")

Enter the number of words you want to input : 5


5


Word : eo
Word : po
Word : qo
Word : lo
Word : ro


eo, lo, po, qo, ro, 

In [6]:
#  Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.  

import string 

x = input("Enter any string :")
s = x.upper()
print (s)

Enter any string : Enter the number of words you want to input


ENTER THE NUMBER OF WORDS YOU WANT TO INPUT


In [11]:
# Write a program that accepts a sequence of whitespace-separated words as input and prints 
# the words after removing all duplicate words and sorting them alphanumerically.  

x = input("Enter any string :")
y = x.split(" ")
y.sort()
z = set(y)
print(z)

Enter any string : Enter any string : Enter the number of words you want to input


{'want', 'string', 'input', 'Enter', 'of', 'you', 'the', ':', 'number', 'words', 'to', 'any'}


In [17]:
# Write a program that accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. 
# The numbers that are divisible by 5 are to be printed in a comma-separated sequence. 

s = str(input("Enter the sequence of comma separated 4 digit binary numbers :"))
print (s)
x = s.split(",")
for z in x:
    z = int(z)
    if (z%5 == 0):
        print(z, end = ", ")

Enter the sequence of comma separated 4 digit binary numbers : 0100,0011,1010,1001


0100,0011,1010,1001
100, 1010, 

In [20]:
# Data of XYZ company is stored in the sorted list. Write a program for searching specific data from that list. 

dataxyz = str(input("Enter the sequence of comma separated 4 digit binary numbers :"))
print (s)
x = s.split(",")
x.sort()

find = str(input("Enter data you want to search :"))
l = -1
for z in x:
    l = l + 1
    if (find == z):
        print(str(find) + " Data found at " + str(l) + "th position of list")

Enter the sequence of comma separated 4 digit binary numbers : 0100,0011,1010,1001


0100,0011,1010,1001


Enter data you want to search : 1001


1001 Data found at 2th position of list
