In [12]:
# Import libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# import the metrics class
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import cross_val_score
from numpy import mean
from numpy import std
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [13]:
df = pd.read_csv("breast-cancer-data.csv")
X = df.iloc[:,2:]    
y = df["diagnosis"]
#print(x,y)

In [14]:
# Using PCA and then LR, RandomForest, Decision Tree

pca = PCA(n_components=3)
scaler = StandardScaler()
pca.fit(X)
Xx = pca.transform(X)
Xxx = pd.DataFrame(Xx)
Xxx.index = X.index
Xxx.columns = ['PC1','PC2','PC3']
print(Xxx.head())
print(pca.explained_variance_ratio_)

           PC1         PC2        PC3
0  1160.142574 -293.917544  48.578398
1  1269.122443   15.630182 -35.394534
2   995.793889   39.156743  -1.709753
3  -407.180803  -67.380320   8.672848
4   930.341180  189.340742   1.374801
[0.98204467 0.01617649 0.00155751]


In [15]:
# LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(Xxx, y, test_size=0.25, random_state=16)

# instantiate the model (using the default parameters)
logreg = LogisticRegression(random_state=16)

# fit the model with data
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy :")
acc = accuracy_score(y_test,y_pred)
print(acc)

[[88  3]
 [ 8 44]]
Accuracy :
0.9230769230769231


In [17]:
# RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(Xxx, y, test_size=0.25, random_state=16)

# instantiate the model (using the default parameters)
logreg = RandomForestClassifier()

# fit the model with data
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy :")
acc = accuracy_score(y_test,y_pred)
print(acc)

[[87  4]
 [ 8 44]]
Accuracy :
0.916083916083916


In [18]:
# Decision Tree

X_train, X_test, y_train, y_test = train_test_split(Xxx, y, test_size=0.25, random_state=16)

# instantiate the model (using the default parameters)
logreg = DecisionTreeClassifier()

# fit the model with data
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy :")
acc = accuracy_score(y_test,y_pred)
print(acc)

[[85  6]
 [11 41]]
Accuracy :
0.8811188811188811
