In [5]:
#1 Make a corpus of 3 sentences

import nltk
import re
from nltk.tokenize import word_tokenize as wt
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
from nltk.probability import FreqDist
import pandas as pd

def MakeCorpus(S1, S2, S3):
    S1_tokens = wt(S1)
    S2_tokens = wt(S2)
    S3_tokens = wt(S3)
    all_tokens = set(S1_tokens).union(set(S2_tokens)).union(set(S3_tokens))
    return(all_tokens, S1_tokens, S2_tokens, S3_tokens)

S1 = 'India won the match'
S2 = 'England won the cricket match'
S3 = 'Australia won the final match'
MakeCorpus(S1, S2, S3)

({'Australia', 'England', 'India', 'cricket', 'final', 'match', 'the', 'won'},
 ['India', 'won', 'the', 'match'],
 ['England', 'won', 'the', 'cricket', 'match'],
 ['Australia', 'won', 'the', 'final', 'match'])

In [6]:
#2.Write a program to input three sentences from user and convert them into vectors.    
# Use presence and absence of words to build the vectors. 

import pandas as pd
import numpy as np
import nltk
from nltk import word_tokenize

def PresenceAbsenceVectorization(S1, S2, S3):
    all_tokens, S1_tokens, S2_tokens, S3_tokens = MakeCorpus(S1, S2, S3)
    review1_dict = dict.fromkeys(all_tokens,0)
    review2_dict = dict.fromkeys(all_tokens,0)
    review3_dict = dict.fromkeys(all_tokens,0)
    for token in S1_tokens:
        review1_dict[token]+=1
    for token in S2_tokens:
        review2_dict[token]+=1
    for token in S3_tokens:
        review3_dict[token]+=1
    reviews_Dict_DF = pd.DataFrame([review1_dict,review2_dict,review3_dict])
    print(reviews_Dict_DF)
    
S1 = 'India won the match'
S2 = 'England won the cricket match'
S3 = 'Australia won the final match'
PresenceAbsenceVectorization(S1, S2, S3)

   the  cricket  Australia  final  England  India  match  won
0    1        0          0      0        0      1      1    1
1    1        1          0      0        1      0      1    1
2    1        0          1      1        0      0      1    1


In [13]:
#3  Write a program to enter 3 strings from a user and vectorise them on basis of their counts.   

from sklearn.feature_extraction.text import CountVectorizer

def CountVectorization(S1, S2, S3):
    review_list = ['tremendous', '100', '%', 'varietal', 'wine', 'hail', 'Oakville', 'aged', 'three', 'year', 'oak', '.', 'Juicy', 'red-cherry', 'fruit', 'compelling', 'hint', 'caramel', 'greet', 'palate', ',', 'framed', 'elegant', ',', 'fine', 'tannin', 'subtle', 'minty', 'tone', 'background', '.', 'Balanced', 'rewarding', 'start', 'finish', ',', 'year', 'ahead', 'develop', 'nuance', '.', 'Enjoy', '2022–2030', '.']
    count_vect = CountVectorizer()
    X_counts = count_vect.fit_transform(review_list)
    print(X_counts.toarray())
    type(X_counts)
    X_names = count_vect.get_feature_names_out()
    a = pd.DataFrame(X_counts.toarray(),columns=X_names)
    #print(a)

S1 = 'India won the match'
S2 = 'England won the cricket match'
S3 = 'Australia won the final match'
CountVectorization(S1, S2, S3)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
#4 Write a program to input 3 strings but vectorise them using 
# TF-IDF (Term Frequency and Inverse Document Frequency) and print the strings along with the vectors. 

from sklearn.feature_extraction.text import TfidfVectorizer

def TFIDFVectorization(S1, S2, S3):
    tf_vect = TfidfVectorizer(min_df=1,lowercase=True,stop_words='english')
    review_list = [S1,S2,S3]
    tf_matrix = tf_vect.fit_transform(review_list)
    type(tf_matrix)
    tf_matrix.shape
    tf_names = tf_vect.get_feature_names_out()
    tf_df = pd.DataFrame(tf_matrix.toarray(),columns=tf_names)
    print(tf_df)

S1 = 'India won the match'
S2 = 'England won the cricket match'
S3 = 'Australia won the final match'
TFIDFVectorization(S1, S2, S3)

   australia   cricket   england     final     india     match       won
0   0.000000  0.000000  0.000000  0.000000  0.767495  0.453295  0.453295
1   0.000000  0.608845  0.608845  0.000000  0.000000  0.359594  0.359594
2   0.608845  0.000000  0.000000  0.608845  0.000000  0.359594  0.359594
